```{r setup-knitr, include = FALSE}
library(knitr)
options(htmltools.dir.version = FALSE)
options(knitr.duplicate.label = "allow")

opts_chunk$set(
  fig.align = "center", 
  fig.retina = 6,
  fig.dim = c(4, 3.5), 
  out.width = "100%", 
  warning = FALSE, 
  message = FALSE,
  #fig.path='images/',
  cache = FALSE,
  echo = FALSE,
  warning = FALSE, 
  message = FALSE
)
```


```{r libraries, include = F, cache = F}
#--- load packages ---#
suppressMessages(library(data.table))
suppressMessages(library(DT))
suppressMessages(library(tmap))
suppressMessages(library(extrafont))
suppressMessages(library(ggthemes))
suppressMessages(library(RColorBrewer))
suppressMessages(library(parallel))
suppressMessages(library(tidyverse))
suppressMessages(library(flipbookr))
suppressMessages(library(flair))
suppressMessages(library(fontawesome))
suppressMessages(library(xaringanExtra))
suppressMessages(library(RefManageR))
```


```{r xaringanExtra, echo=FALSE, cache = F}
# You can do like this. 
# xaringanExtra::use_xaringan_extra(
#   c(
#     "tile_view", 
#     "animate_css", 
#     "tachyons",
#     "animate_css"
#     )
#   )

use_animate_css()
use_tile_view()
use_panelset()
use_clipboard()
use_scribble()
use_search(
  show_icon = TRUE, 
  auto_search=FALSE
)
use_extra_styles(
  hover_code_line = TRUE,
  mute_unhighlighted_code = TRUE
)
use_progress_bar(
  color = "#ffb71e",
  location = "bottom"
)
```



```{r setup-bib, include=FALSE, cache = FALSE}
#/*--------------------------------*/
#' ## # For citation
#/*--------------------------------*/
BibOptions(
  check.entries = FALSE,
  bib.style = "authoryear",
  style = "markdown",
  hyperlink = FALSE,
  dashed = TRUE,
  max.names = 2,
  longnamesfirst = FALSE
)
# bib <- ReadBib("../../GitControlled/Writing/ref.bib")
bib <- ReadBib("ref.bib")
# for example,
# `r Citet(bib, "deschenes2007economic")`

# BibOptions(max.names = 2)
```